% 18.02.18: MM, JK
ParameterInit;

K = [IR, Cpsi];


% options = optimoptions(@fminunc,...
%                        'Algorithm', 'quasi-newton',...
%                        'HessUpdate', 'bfgs',...
%                        'MaxFunEvals', 10000,...
%                        'MaxIter', 100,...
%                        'TolFun', 1e-8,...
%                        'Display', 'off');
% [xmin, xfmin, exitflag, output, gradinx] = fminunc(@errorFunction, K, options);

options = optimset('MaxFunEvals', 200);
K = fminsearch('errorFunction', K, options);