% 17.02.18, MM,options = optimset('MaxFunEvals', 200);
ParameterInit;

K = [K1, K2, K3, K4, K5, K6];
options = optimset('MaxFunEvals', 2000);
[K, fmin, exitflag, output] = fminsearch('errorFunction', K, options);

% options = optimoptions(@fminunc,...
%                        'Algorithm', 'quasi-newton',...
%                        'HessUpdate', 'bfgs',...
%                        'MaxFunEvals', 2000,...
%                        'MaxIter', 20,...
%                        'TolFun', 1e-8,...
%                        'Display', 'off');
% [xmin, xfmin, exitflag, output, gradinx] = fminunc(@errorFunction, K, options);
                       